<div class="doctitle">Qui sommes nous ?
    <div class="lineorange"></div>
</div>

<div class="paragraphe">
    <img src="<?php echo $this->baseUrl('images/flecheexplication.png'); ?>" width="23" height="24" style="margin: 0 10px 10px;float:left;" alt=""/>	

    <h1>Comment est né decorezrenovez.fr ?</h1>
    <div class="info">Plus que d'une tendance, decorezrenovez.fr est né d'un besoin</div>

    <p>C’est en cherchant de l’aide pour réaliser des travaux qu’est venue l’idée de ce site. 
        Chercher un plombier, négocier le prix, savoir si cette personne introuvable pourra également m’aider pour installer la lumière et m’expliquer les astuces pour installer mon carrelage.. etc
    </p>
    <p> 
        Je me suis simplement dis j’ai un budget de tant j’ai besoin d’aide pour certaines choses comme l’électricité ou la plomberie aucun outils ne me permet de faire cette recherche alors je vais le créer en utilisant toutes mes connaissances
        dans le web pour que l’outils facilite au mieux les choses. Ainsi decorezrenovez est né.
    </p> 
</div>

<div class="paragraphe">
    <img width="23" height="24" style="margin: 0 10px 10px;float:left;" src="<?php echo $this->baseUrl('images/flecheexplication.png'); ?>" alt="">
    <h1>Que permet decorezrenovez en 3 clics ? </h1>
    <div class="info">decorezrenovez.fr est fait pour faciliter la vie de l'internaute</div>

    <p>Pour le particulier decorezrenovez permet en 3 clics de :</p>
    <ul>
        <li>Trouver un artisant près de chez soi</li>
        <li>Avoir un descriptif, notation et avis pour être plus confiant</li>
        <li>Selectionner un artisant selon ses aptitudes</li>
        <li>Prénégocier un prix de base pour savoir à quoi s’attendre <img width="67" height="16" src="/images/pictonouveau.jpg" alt="nouveau"></li>
        <li>Contacter librement l’artisant de son choix</li>
    </ul>
</div>

<div class="paragraphe">
    <img width="23" height="24" style="margin: 0 10px 10px;float:left;" src="<?php echo $this->baseUrl('images/flecheexplication.png'); ?>" alt="">
    <h1>Que permet decorezrenovez à un entrepreneur de chantier en 4 min ? </h1>
    <div class="info">Un outils adapté autant pour le particulier que pour le professionnel</div>

    <p>Pour entrepreneur de chantier decorezrenovez permet en 4 minutes de :</p>
    <ul>
        <li>Poser son annonce simplifiée et prénégociée de chantier</li>
        <li>Se faire contacter par des professionnels sérieux qui prendront en charge le chantier</li>
    </ul>
</div>

