<div class="doctitle">Conditions générales de vente et descriptif du service
    <div class="lineorange"></div>
</div>

<p>Professionnel, je déclare détenir les certifications me donnant la droit d’exercer. Je ne suis pas professionnel, je déclare réaliser le nombre d’heure légalement autorisé.</p>

<div class="paragraphe">
    <img src="<?php echo $this->baseUrl('images/flecheexplication.png'); ?>" width="23" height="24" style="margin: 0 10px 10px;float:left;" />	
    <h1>Modification d'une annonce</h1>
    <div class="info"></div>

    <p>Cette option est payante. Elle coûte 2 € TTC (1,67 € HT), payables par carte bancaire. 
        Seuls certains champs de votre annonce sont modifiables :</p>
    <br />
    <ul>
        <li>Votre nom (*)</li>
        <li>Votre numéro de téléphone</li>
        <li>Le titre de votre annonce</li>
        <li>Les paramètres spécifiques à la catégorie</li>
        <li>Le descriptif</li>
        <li>Le prix</li>
        <li>Les photos</li>
    </ul>
    <br />

    <p>(*) non modifiable pour les professionnels avec Compte Pro 
        Votre annonce modifiée sera de nouveau validée par decorezrenovez.fr avant sa diffusion. 
        Au cours de la modification de votre annonce vous pouvez également souscrire aux options payantes « Remonter mon annonce en tête de liste » (à partir de 5,02 € HT soit 6 € TTC), « Ajouter un Logo Urgent » (3,34 € HT soit 4 € TTC) et « Mettre mon annonce A la Une » (à partir de 8,36 € HT soit 10 € TTC). 
        Si votre annonce modifiée est refusée par decorezrenovez.fr en raison de sa non conformité aux règles de diffusion, votre paiement par carte bancaire sera annulé. Vous recevrez un email d'information. 
        Si votre annonce modifiée est validée par decorezrenovez.fr, cette dernière remplacera l'ancienne version de votre annonce. Elle apparaîtra alors en début de liste sur le site decorezrenovez.fr. Nous vous précisons que les annonces sont classées sur le site decorezrenovez.fr par ordre chronologique en fonction de la date et de l'heure de mise en ligne, par conséquent le positionnement en début de liste de votre annonce n'est que provisoire. 
        En revanche, la durée de diffusion de votre annonce ne sera pas prolongée. Elle reste de deux mois à partir de la date initiale de mise en ligne de l'annonce sauf retrait anticipé de cette dernière par decorezrenovez.fr, conformément à l'article 2.4 des conditions générales de diffusion. En conséquence, les éventuelles options souscrites lors de la modification de votre annonce prendront fin dès que l'annonce ne sera plus en ligne et elles ne pourront pas être transférées à une autre annonce. 
        Aucun remboursement n'est possible après la mise en ligne de votre annonce modifiée.</p> 
</div>

<div class="paragraphe">
    <img src="<?php echo $this->baseUrl('images/flecheexplication.png'); ?>" width="23" height="24" style="margin: 0 10px 10px;float:left;" />	
    <h1>Remonter mon annonce en tête de liste :</h1>
    <div class="info"></div>

    <p>Cette option se décline sous forme de trois durées différentes : <br /><br />
        <strong>— Immédiatement : </strong><br />
        L'option « Immédiatement » vous permet de remonter immédiatement votre annonce en haut de la liste de résultats comme si elle venait d'être mise en ligne.
        Pour remonter une annonce immédiatement en tête de liste, rendez-vous sur la page de votre annonce et cliquez sur « Remonter en tête de liste ». Cochez ensuite « Immédiatement » puis cliquez sur Valider.
        Cette option est payante. Vous pouvez payer par carte bancaire 1,60 € TTC (1,34 € HT). 
        Nous vous précisons que les annonces sont classées sur le site decorezrenovez.fr par ordre chronologique et en fonction de la qualité de l'artisant, du nombre de projets réalisé à travers le site, par conséquent le positionnement en début de liste de votre annonce n'est que provisoire. 
        Aucun remboursement n'est possible après l'exécution de la prestation. 
        La durée de diffusion de votre annonce ne sera pas prolongée par le repositionnement en tête de liste. Elle reste de deux mois à partir de la date initiale de mise en ligne de l'annonce, sauf retrait anticipé de cette dernière par decorezrenovez.fr, conformément à l'article 2.4 des conditions générales de diffusion. 
        <br /><br />
        <strong>— Remonter en tête de liste chaque jour pendant 7 jours : </strong><br />
        Cette option est payante. Elle vous sera facturée 18 € TTC (15,05 € HT) pour les annonces de chantier comme pour les profils artisant. L'option est payable par carte bancaire uniquement. 
        Vous pouvez souscrire à cette option au moment du dépôt de votre annonce et ou profil, du prolongement de la durée de vie de celle-ci ou lors d'une modification. 
        Si votre annonce est déjà en ligne, vous pouvez également y souscrire, ainsi qu'à plusieurs autres options en même temps (« Ajouter un Logo » et « Mettre mon annonce en tête de liste »), depuis la page de votre annonce. 
        Votre annonce sera validée par decorezrenovez.fr avant sa diffusion. 
        Si votre annonce est refusée par decorezrenovez.fr en raison de sa non conformité aux règles de diffusion, votre paiement par carte bancaire pour l'option « Remonter en tête de liste chaque semaine » sera annulé. Vous recevrez un email d'information. 
        Si votre annonce est validée par decorezrenovez.fr, elle sera mise en ligne sur le site decorezrenovez.fr. Par la suite, votre annonce sera positionnée en début de liste sur le site decorezrenovez.fr chaque jour pendant 7 jours consécutifs à la date anniversaire de la souscription à l'option, pendant sa période de mise en ligne. Un email vous sera envoyé pour vous confirmer la souscription à l'option et un autre au lendemain de la péremption de l'option, soit le 8ième jour, afin de vous en informer. 
        Par ailleurs, l'abonnement au service prend fin dès que l'annonce n'est plus en ligne et il ne peut pas être transféré à une autre annonce. 
        Nous vous précisons que les annonces chantier sont classées sur le site decorezrenovez.fr par ordre chronologique en fonction de la date et de l'heure de mise en ligne. Par conséquent, le positionnement en début de liste de votre annonce n'est que provisoire. 
        La durée de diffusion de votre annonce ne sera pas prolongée par le repostionnement quotidien pendant 7 jours en tête de liste. Elle reste de deux mois à partir de la date initiale de mise en ligne de l'annonce, sauf retrait anticipé de cette dernière par vos soins ou par decorezrenovez.fr, conformément à l'article 2.4 des conditions générales de diffusion. 
        Aucun remboursement n'est possible après l'exécution de la prestation ou au-delà du délai légal de rétractation. <br />
        <br /><br />
        <strong>— Remonter en tête de liste chaque semaine pendant la durée de vie de l'annonce : </strong><br />
        Cette option est payante. Elle vous sera facturée 12 € TTC (10,03 € HT) dans les catégories immobilier et véhicules (à l'exception des catégories équipement auto, équipement moto et équipement caravaning). Elle vous sera facturée 6 € TTC (5,02 € HT) dans toutes les autres catégories. L'option est payable par carte bancaire uniquement. 
        Vous pouvez souscrire à cette option au moment du dépôt de votre annonce ou, si votre annonce est déjà en ligne, sur la page de votre annonce. Si votre annonce est déjà en ligne, vous pouvez souscrire à plusieurs options en même temps (« Remonter en tête de liste chaque semaine pendant la durée de vie de l'annonce », « Ajouter un Logo Urgent » et « Mettre mon annonce en tête de liste »). 
        Pour remonter toutes les semaines en tête de liste, rendez-vous sur la page de votre annonce et cliquez sur « Remonter en tête de liste ». Sélectionnez ensuite « Remonter en tête de liste chaque semaine pendant la durée de vie de l'annonce » puis cliquez sur Valider. 
        Vous pouvez également souscrire à cette option au cours de la modification de votre annonce. 
        Votre annonce sera validée par decorezrenovez.fr avant sa diffusion. 
        Si votre annonce est refusée par decorezrenovez.fr en raison de sa non conformité aux règles de diffusion, votre paiement par carte bancaire pour l'option Remonter en tête de liste chaque semaine sera annulé. Vous recevrez un email d'information. 
        Si votre annonce est validée par decorezrenovez.fr, elle sera mise en ligne sur le site decorezrenovez.fr. Par la suite, votre annonce sera positionnée en début de liste sur le site decorezrenovez.fr chaque semaine à la date anniversaire du dépôt de votre annonce, pendant sa période de mise en ligne. Un email vous sera envoyé à chaque positionnement de votre annonce en tête de liste (chaque semaine à la date anniversaire du dépôt de votre annonce). 
        L'abonnement au service prend fin dès que l'annonce n'est plus en ligne et il ne peut pas être transféré à une autre annonce. 
        Nous vous précisons que les annonces sont classées sur le site decorezrenovez.fr par ordre chronologique en fonction de la date et de l'heure de mise en ligne, par conséquent le positionnement en début de liste de votre annonce n'est que provisoire. 
        La durée de diffusion de votre annonce ne sera pas prolongée par le repositionnement hebdomadaire en tête de liste. Elle reste de deux mois à partir de la date initiale de mise en ligne de l'annonce, sauf retrait anticipé de cette dernière par decorezrenovez.fr, conformément à l'article 2.4 des conditions générales de diffusion. 
        Aucun remboursement n'est possible après l'exécution de la prestation ou au-delà du délai légal de rétractation. 
    </p> 
</div>

<div class="paragraphe">
    <img src="<?php echo $this->baseUrl('images/flecheexplication.png'); ?>" width="23" height="24" style="margin: 0 10px 10px;float:left;" />	
    <h1>Ajouter un logo de démarquation</h1>
    <div class="info"></div>

    <p>Cette option est payante. Elle coûte 4 € TTC (3,34 € HT), payables par carte bancaire. 
        Vous pouvez souscrire à cette option au moment du dépôt de votre annonce ou, si votre annonce est déjà en ligne, sur la page de votre annonce. Si votre annonce est déjà en ligne, vous pouvez souscrire à plusieurs options en même temps (« Remonter mon annonce en tête de liste », « Ajouter un Logo Urgent » et « Mettre mon annonce A la Une »). 
        Pour afficher un logo urgent sur votre annonce, rendez-vous sur la page de votre annonce et cliquez sur « Mettre en avant ». Cochez ensuite « Ajouter un Logo Urgent » puis cliquez sur Continuer. 
        Vous pouvez également souscrire à cette option au cours de la modification de votre annonce. 
        Votre annonce sera validée par decorezrenovez.fr avant sa diffusion. 
        Si votre annonce est refusée par decorezrenovez.fr en raison de sa non conformité aux règles de diffusion, votre paiement par carte bancaire sera annulé. Vous recevrez un email d'information. 
        Si votre annonce est validée par decorezrenovez.fr, elle sera mise en ligne sur le site decorezrenovez.fr et sera signalée par un logo et un encart rouge dans la liste de résultats. 
        La durée de diffusion de votre annonce est de deux mois à partir de la date initiale de mise en ligne de l'annonce sauf retrait anticipé de cette dernière par decorezrenovez.fr, conformément à l'article 2.4 des conditions générales de diffusion. 
        Aucun remboursement n'est possible après la mise en ligne de votre annonce. </p> 
</div>

<div class="paragraphe">
    <img src="<?php echo $this->baseUrl('images/flecheexplication.png'); ?>" width="23" height="24" style="margin: 0 10px 10px;float:left;" />	
    <h1>Mettre mon annonce en tête de liste : </h1>
    <div class="info"></div>

    <p>Cette option est payante. Elle coûte :</p><br />
    <ul>
        <li>10 € TTC (8,36 € HT) pour une durée de 7 jours.</li>
        <li>30 € TTC (25,08 € HT) pour une durée de 30 jours.</li>
    </ul><br />

    <p>Cette option est payable par carte bancaire.
        <br /><br />
        L'Annonce devra posséder au moins une photo, proposer une offre de bien (et non une demande) et ne pas être déposée dans l'une des catégories suivantes : Emploi, Billetterie, Evènements et Cours Particuliers. 
        Il est possible de souscrire à cette option au moment du dépôt d'une Annonce ou, pendant qu'elle est en ligne, sur la page de l'Annonce. Si l'Annonce est déjà en ligne, vous pouvez souscrire à plusieurs options en même temps (« Remonter mon annonce en tête de liste », « Ajouter un Logo Urgent » et « Mettre mon annonce en tête de liste »). 
        Si la durée de mise en ligne de votre annonce avant sa suppression est strictement inférieure à 21 jours, vous ne pourrez souscrire à l'option que pour une durée de 7 jours. 
        <br /><br />
        Il est aussi possible de souscrire à cette option pendant la modification d'une Annonce. 
        L'Annonce sera validée par LBC FRANCE avant sa diffusion. 
        Si l'Annonce est refusée par LBC FRANCE au moment du dépôt, en raison de sa non-conformité aux règles de diffusion, le paiement par carte bancaire de l'option « Mettre mon annonce A la Une » sera annulé. Un email d'information vous sera envoyé. 
        Si l'Annonce est validée par LBC FRANCE, elle sera mise en ligne sur le Site Internet. 
        L'Annonce pourra être mise en avant au maximum avec deux autres Annonces. Les Annonces bénéficiant de l'option « A la Une » s'afficheront de manière aléatoire, une Annonce ne sera donc pas visible en permanence sur le Site Internet. 
        La durée de diffusion de l'Annonce, indépendamment de la souscription de l'option « A la Une », reste de deux mois à partir de la date initiale de mise en ligne de l'Annonce sauf retrait anticipé de cette dernière par LBC FRANCE, conformément à l'article 2.4 des conditions générales de diffusion. 
        Dès la fin de la durée de l'option « A la Une », un email sera envoyé à l'Annonceur pour proposer une nouvelle diffusion de l'Annonce avec l'option « A la Une ». 
        Aucun remboursement n'est possible après l'exécution de la prestation. 
        <br /><br />
        Votre annonce sera relue par decorezrenovez.fr avant sa diffusion. 
        Si votre annonce est refusée par decorezrenovez.fr en raison de sa non conformité aux règles de diffusion, vous recevrez un email d'information. 
        Si votre annonce est validée par decorezrenovez.fr, elle sera mise en ligne sur le site decorezrenovez.fr. 
        Elle reste deux mois en ligne à partir de la date initiale de mise en ligne de l'annonce, sauf retrait anticipé de cette dernière par decorezrenovez.fr, conformément à l'article 2.4 des conditions générales de diffusion. 
        Aucun remboursement n'est possible après l'exécution de la prestation. </p> 
</div>	
</div>