<div class="doctitle">Partenaires
    <div class="lineorange"></div>
</div>

<div class="paragraphe">
    <img src="<?php echo $this->baseUrl('images/flecheexplication.png'); ?>" width="23" height="24" style="margin: 0 10px 10px;float:left;" alt=""/>	

    <h1>Devenez partenaires privillégiés de decorez-renovez.fr.</h1>
    <div class="info"> Contactez-nous pour échanger et faire parti de nos collaborateurs </div>

    <p>Profitez de la puissante audience de <a href="page1.html">decorez-renovez.fr</a> en communiquant auprès de nombreux visiteurs.

        Profitez de nos espaces publicitaires et de la performance de nos outils de communication<a href="page1.html">Devenir partenaire</a></p> 


    
</div>	

<div class="paragraphe">
    <img width="23" height="24" style="margin: 0 10px 10px;float:left;" src="<?php echo $this->baseUrl('images/flecheexplication.png'); ?>" alt="">
    <h1>Nos principaux partenaires</h1>
    <div class="info"></div>
    
    <div class="leftColumn">
        <img width="299" height="122" style="margin: 0 10px 10px;" src="<?php echo $this->baseUrl('images/partenaire1.jpg'); ?>" alt="">
    </div>
    <div class="rightColumn">
        <h1>You Recycle</h1>

        <p>Le souci de Yourecycle pour l’environnement se traduit non seulement par son activité recyclage mais aussi par un management environnemental interne. C’est grâce à cet engagement que Yourecycle bénéficie de la certification ISO 14001. Cette certification repose sur le principe d'amélioration continue de la performance environnementale par la maîtrise des impacts. 
            Délais de paiement : dans les 4 jours ouvrables après réception et après vérification de l’état.
            Mode de paiement : virement bancaire ou don à une association parmi les associations partenaires de Yourecycle.</p>

    </div>
</div>

<div class="paragraphe">
    <div class="leftColumn">
        <img width="299" height="122" style="margin: 0 10px 10px;" src="<?php echo $this->baseUrl('images/partenaire1.jpg'); ?>" alt="">
    </div>
    <div class="rightColumn">
        <h1>You Recycle</h1>

        <p>Le souci de Yourecycle pour l’environnement se traduit non seulement par son activité recyclage mais aussi par un management environnemental interne. C’est grâce à cet engagement que Yourecycle bénéficie de la certification ISO 14001. Cette certification repose sur le principe d'amélioration continue de la performance environnementale par la maîtrise des impacts. 
            Délais de paiement : dans les 4 jours ouvrables après réception et après vérification de l’état.
            Mode de paiement : virement bancaire ou don à une association parmi les associations partenaires de Yourecycle.</p>

    </div>
</div>

<div class="paragraphe">
    <img width="23" height="24" style="margin: 0 10px 10px;float:left;" src="<?php echo $this->baseUrl('images/flecheexplication.png'); ?>" alt="">
    <h1>Vous avez un Gros Chantier et vous cherchez la meilleure offre ?</h1>
    <div class="info">L’équipe decorezrenovez.fr vous permet d’être accessible facilement par des professionnels sérieux qui vous proposeront leurs devis</div>

    <p>L’équipe decorezrenovez.fr vous permet d’être accessible facilement par des professionnels sérieux qui vous proposeront leurs devis</p>
</div>