<div class="doctitle">Publicit&eacute; sur decorezrenovez.fr
    <div class="lineorange"></div>
</div>

<div class="leftColumn inner">
    
    <div class="inner">
        <p>Déposer votre profil sur <a href="page1.html">decorez-renovez.fr</a> est GRATUIT et très simple.
            Votre annonce sera validée par notre équipe éditoriale avant d’être mise en ligne.<a href="/index/regle-de-diffusion">Voir les règles de diffusion.</a></p>
    </div>

    <div class="inner">
        <img src="/images/flecheexplication.png" width="23" height="24" style="margin: 0 10px 10px;float:left;" alt=""/>	

        <h1>Vous souhaitez communiquer sur decorezrenovez.fr ?</h1>
        <div class="info">decorezrenovez.fr est un outils puissant pour vous faire connaître.</div>

        <p>Profitez de la puissante audience de <a href="page1.html">decorez-renovez.fr</a> en communiquant auprès de nombreux visiteurs.<a href="page1.html"> > Déposez votre profil !</a>

            La commercialisation de ces espaces publicitaires est assurée par <a href="page1.html">decorez-renovez.fr</a></p> 

        <div class="paragraphe">
            <img width="23" height="24" style="margin: 0 10px 10px;float:left;" src="<?php echo $this->baseUrl('images/flecheexplication.png'); ?>" alt="">
            <h1>Vous êtes une structure de vente de produit de travaux bricolage ou BTP ? </h1>
            <div class="info">decorezrenovez.fr s'occupe de vous faire la pub</div>

            <p>Profitez de notre espace publicitaire réservé et ciblé réflechi pour être <strong>extrêmement efficace </strong> et en même temps discret pour l’utilisateur.</p>
        </div>
        <div class="leftColumn inner">
            <img width="424" height="416" style="margin: 0 10px 10px;float:left;" src="<?php echo $this->baseUrl('images/imgpagepub.jpg'); ?>" alt="pub">
        </div>
        <div class="leftColumn inner">
            <h1>2 formats sont disponibles :</h1>

            <p>Méga-bandeau : 720x90 Skyscraper : 120x600</p>
            <div class="paragraphe">
                <h1>1 habillage TOTAL</h1>

                <p>SKIN HTML/CSS - Arrière</p>
            </div>
        </div>
    </div>	
</div>

<div class="inner">	
    <img width="23" height="24" style="margin: 0 10px 10px;float:left;" src="<?php echo $this->baseUrl('images/flecheexplication.png'); ?>" alt="">
    <h1>Vous avez un Gros Chantier et vous cherchez la meilleure offre ?</h1>
    <div class="info">L’équipe decorezrenovez.fr vous permet d’être accessible facilement par des professionnels sérieux qui vous proposeront leurs devis</div>

    <p>L’équipe decorezrenovez.fr vous permet d’être accessible facilement par des professionnels sérieux qui vous proposeront leurs devis</p>
</div>

<div class="inner">	
    <img width="23" height="24" style="margin: 0 10px 10px;float:left;" src="<?php echo $this->baseUrl('images/flecheexplication.png'); ?>" alt="">
    <h1>Devenez partenaire de decorezrenovez.fr !</h1>
    <div class="info">L’équipe decorezrenovez.fr s’occupe de ses partenaires.</div>

    <p> Elle peut également prendre en charge l’envoi de vos emailing.</p>
</div>	