<?php
$link = 'http://'.$_SERVER['HTTP_HOST'].'/';
?>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
    <input type="hidden" name="amount" value="<?php echo round($this->offer->getPrice()/1000*6, 2); ?>">
        
    <input name="currency_code" type="hidden" value="EUR" />
    <input name="shipping" type="hidden" value="0.00" />
    <input name="tax" type="hidden" value="0.00" />
    <input name="return" type="hidden" value="<?php echo $link; ?>annonce/show/id/<?php echo $this->offer->getAnnonce()->getId(); ?>" />
    <input name="cancel_return" type="hidden" value="<?php echo $link; ?>offer/validate/id/<?php echo $this->offer->getId(); ?>" />
    <input name="notify_url" type="hidden" value="<?php echo $link; ?>offer/makevalidate" />
    <input name="cmd" type="hidden" value="_xclick" />
    <input name="business" type="hidden" value="paiement@decorezrenovez.fr" />
    <input name="item_name" type="hidden" value="Proposer un devis" />
    <input name="no_note" type="hidden" value="1" />
    <input name="lc" type="hidden" value="FR" />
    <input name="bn" type="hidden" value="PP-BuyNowBF" />
    <input name="custom" type="hidden" value="offer_id=<?php echo $this->offer->getId(); ?>" />
    <input alt="Effectuez vos paiements via PayPal : une solution rapide, gratuite et sécurisée" name="submit" src="https://www.paypal.com/fr_FR/FR/i/btn/btn_buynow_LG.gif" type="image" /><img src="https://www.paypal.com/fr_FR/i/scr/pixel.gif" border="0" alt="" width="1" height="1" />
</form>