<?php
$link = 'http://'.$_SERVER['HTTP_HOST'].'/';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="description" content="Trouvez facilement des vidéos démos pour faire vos travaux ..des conseils et astuces pour réaliser tous vos travaux vous-même !" />
    <meta name="keywords" content="video , travaux , décorer, renover , bricolage , comment faire , Chauffage , Chef de chantier, carrelage , peinture , parquet , plomberie , maçonnerie , extérieure , menuiserie , robinet , lampe , construire , batir , aménager , frotter , lustrer , faire , technique , electricite , ramonage , pose , bois  , ciment , platre , plafond , sols , murs , lumière , portes , réaliser , décoration , tenir , plaquer , bureau , dehors , dedans , intérieur , extérieur , linteau , outils , bricolage , complexe , tuyaux , facile , difficile , placo , tuiles , scie , marteau , recherche , produire , fondations , canalisations" />
    <title>travauxafaire.fr toutes les videos et conseils pour faire ses travaux soi-même !</title>
    <link href="templates/default/style.css" rel="stylesheet" type="text/css" media="all" />
    <link rel="shortcut icon" href="images/favicon.ico" type="images/favicon" />   
</head>

<body>
    <table width="0" border="0" cellpadding="0" cellspacing="0">
        <tr>
            <td>
                <table width="411" border="0" cellpadding="0" cellspacing="0">
                    <tr>
                        <td>
                            <a href="http://www.decorezrenovez.fr" target="_blank">
                                <img src="<?php echo $link; ?>images/mail/emailing-decoup_01.jpg" width="255" height="327" alt="www.decorezrenovez l'outils indispensable pour vos travaux" longdesc="http://www.travauxafaire.fr" />
                            </a>
                        </td>
                        <td width="89">
                            <table width="0" border="0" cellpadding="0" cellspacing="0">
                                <tr>
                                    <td width="255">
                                        <a href="www.decorezrenovez.fr" target="_blank">
                                            <img src="<?php echo $link; ?>images/mail/emailing-decoup_02.jpg" width="255" height="20" longdesc="http://www.travauxafaire.fr" />
                                        </a>
                                    </td>
                                </tr>
          <tr>
            <td width="255"height="54" bgcolor="#fff"><font face="Tahoma" size="2" color="#1979ce">Bravo Mr <?php echo $this->member->getLastname(); ?> !
votre inscription à été effectuée avec succès</font><font face="Tahoma" size="4" color="#955799">&nbsp;</font></td>
          </tr>
          <tr>
            <td><a href="http://www.travauxafaire.fr"><img src="<?php echo $link; ?>images/mail/emailing-decoup_05.jpg" width="255" height="4" longdesc="http://www.travauxafaire.fr" /></a></td>
          </tr>
          <tr>
            
            <td width="255" height="56" bgcolor="#fff"><font face="Tahoma" size="2" color="#1979ce">Vous pouvez désormais contacter les prestataires et poser vos avis.</font><font face="Tahoma" size="4" color="#955799">&nbsp;</font></td>
          </tr>
          <tr>
            <td><a href="www.decorezrenovezfr" target="_blank"><img src="<?php echo $link; ?>images/mail/emailing-decoup_07.jpg" width="255" height="20" longdesc="http://www.travauxafaire.fr" /></a></td>
          </tr>
          <tr>
            <td width="255" height="75" bgcolor="#1979ce"><font face="Tahoma" size="2" color="#fff">Vous pouvez également déposer une annonce de chantier des professionnels 

</font><br />
									<font face="Tahoma" size="4" color="#fff">vous contacteront. <br />
									</font></td>
          </tr>
          <tr>
            <td><a href="http://www.decorezrenovez.fr" target="_blank"><img src="<?php echo $link; ?>images/mail/emailing-decoup_09.jpg" width="255" height="98" longdesc="http://www.travauxafaire.fr" /></a></td>
          </tr>
        </table></td>
        <td width="46"><a href="http://www.decorezrenovez.fr" target="_blank"><img src="<?php echo $link; ?>images/mail/emailing-decoup_03.jpg" width="83" height="327" longdesc="http://www.travauxafaire.fr" /></a></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td height="30">
    
    <font face="Tahoma" size="1" color="#955799"> <a href="http://www.decorezrenovez.fr" target="_blank">Suivez-nous sur les réseaux sociaux  </a><br />* certains services optionnels sont payant. </a><br /><a>copyright decorezrenovez.fr - tous droits réservés.  </a></font><br />
  </tr>
</table>
</body>
</html>
