<?php echo $this->doctype() ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Decorez-Renovez.fr l'outil indispensable pour vos travaux</title>
        <link rel="shortcut icon" href="/images/favicon.ico" type="/images/favicon">
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <h1>ADMINISTRATION</h1>
        <div id="wrapper">

            <div class="clear"></div>

            <div id="container">

                <div id="nav">
                    <ul>
                        <li>
                            <a href="<?php echo $this->url(array('controller' => 'membre', 'action' => 'index')); ?>">Rechercher un membre</a>
                            <img src="/images/separation_nav.jpg" width="1" height="21" alt="separation">
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('controller' => 'job', 'action' => 'index')); ?>">Jobs en validation</a>
                            <img src="/images/separation_nav.jpg" width="1" height="21" alt="separation">
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('controller' => 'commentaire', 'action' => 'index')); ?>">Commentaires</a>
                            <img src="/images/separation_nav.jpg" width="1" height="21" alt="separation">
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'annonce', 'action' => 'index')); ?>">Retour</a>
                        </li>
                    </ul>
                </div>

                <div id="content">
                    <?php echo $this->layout()->content ?>
                </div>

            </div>

            <div class="clear"></div>
    </body>
</html>